### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by pborrell** [pborrell/DEV3308_team73#1]
Create a phishing web-app.
This will have randomly selected front end text to try and get people to type in personal information. 
The personal information would be saved into a database and then either an IT department or they will get an email or a text informing them they entered their information into a phishing site.

**Comment by serenabux** [comment]
Create either a web app or a phone app to promote recycling/ composting. 
A user has the ability to look up their item in the app and see if it can be recycled or composted  or if it needs to be trashed.  If possible the app updates based on location since many places have different laws. It also would update at CU to include specific grab and go items (maybe based on user input from the same area).   If the item is recyclable or compostable the app will use location to tell them the nearest place that they can recycle/compost it at (either based on government data or user input, etc).
